### ISSUE TITLE
Wrong length for Tax Key

### ISSUE THREAD

**Issue by MajestyIV** [FluiTec/FluiTec.DatevSharp#4]
The new Datev tax keys can be 4 digits long. Could you fix this, please? Or is there a way to overwrite the validation?

**Comment by IInvocation** [comment]
I made the validation accept 2-4 characters. There's no way to manually override the validation, because i think it's the right way. I only own an (apparently) older specification - and it's quite useful to get issues for changed specification. Any other changes i should know?
Apart from this - i'd always accept pull-requests.
